{
  "formatVersion": "1.1",
  "component": {
    "group": "nulled",
    "module": "injector",
    "version": "1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-1.4.jar",
          "url": "injector-1.4.jar",
          "size": 408597,
          "sha512": "209b97c55ac0d17435473419c0773c799525a8ceb7ee01b4ae5c5eeb241b33db4e4b345fcb299e2b7a0c6097d4411dde27b0b8430819d4f6adfcdecc38ab5077",
          "sha256": "db89f7434c5dcde050ed9b447cab1dfd36793f0222d20a3ba1f4741fbde2fbeb",
          "sha1": "5c6aabcda8bdd1293d3eb627ba79a45e9bcaee1c",
          "md5": "eb7372e5684a63cfca7d2f0263eebac3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-jre"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "6.0-alpha-3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "fernflower",
          "version": {
            "requires": "07082019"
          }
        },
        {
          "group": "nulled",
          "module": "logger",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "nulled",
          "module": "annotations",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-1.4.jar",
          "url": "injector-1.4.jar",
          "size": 408597,
          "sha512": "209b97c55ac0d17435473419c0773c799525a8ceb7ee01b4ae5c5eeb241b33db4e4b345fcb299e2b7a0c6097d4411dde27b0b8430819d4f6adfcdecc38ab5077",
          "sha256": "db89f7434c5dcde050ed9b447cab1dfd36793f0222d20a3ba1f4741fbde2fbeb",
          "sha1": "5c6aabcda8bdd1293d3eb627ba79a45e9bcaee1c",
          "md5": "eb7372e5684a63cfca7d2f0263eebac3"
        }
      ]
    }
  ]
}
