{
  "formatVersion": "1.1",
  "component": {
    "group": "nulled",
    "module": "injector",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-1.1.jar",
          "url": "injector-1.1.jar",
          "size": 408239,
          "sha512": "96eeef5e117aadbd38e5eec01b14321553dd6faaffe5c5408f471d798aa48197d5832229223a76940bf974d86d86368904a963b4beea069aaa41a33cf441bbcc",
          "sha256": "897d8997d929917e671719d33e169bd00fe51373bc44d93c36e3359011b3669a",
          "sha1": "be892360428f4d1c4c3abd6b0b2a7c802654ec31",
          "md5": "cd3a0a1ad9c9837f3f0ce7981ccfdfdb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-jre"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "6.0-alpha-3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "fernflower",
          "version": {
            "requires": "07082019"
          }
        },
        {
          "group": "nulled",
          "module": "logger",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "nulled",
          "module": "annotations",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-1.1.jar",
          "url": "injector-1.1.jar",
          "size": 408239,
          "sha512": "96eeef5e117aadbd38e5eec01b14321553dd6faaffe5c5408f471d798aa48197d5832229223a76940bf974d86d86368904a963b4beea069aaa41a33cf441bbcc",
          "sha256": "897d8997d929917e671719d33e169bd00fe51373bc44d93c36e3359011b3669a",
          "sha1": "be892360428f4d1c4c3abd6b0b2a7c802654ec31",
          "md5": "cd3a0a1ad9c9837f3f0ce7981ccfdfdb"
        }
      ]
    }
  ]
}
