{
  "formatVersion": "1.1",
  "component": {
    "group": "nulled",
    "module": "injector",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-1.2.jar",
          "url": "injector-1.2.jar",
          "size": 408598,
          "sha512": "babe7882d7bb2b829b6252a07a3c4eed990d47651258dd1a0126ad582466a871d1ed76580b32ecf9ae354afeadf5f145d4fd6b25361035b28a01734f0d6fa75a",
          "sha256": "e3b30ac3fa262ac9ef28dad099cfa9e55533cfe4a72e9503fac38a5538aec579",
          "sha1": "8c0e6dac93a0a0a3be520d5fdd1fe93fa63a659d",
          "md5": "28e9b67a78cae6efcbd15f1655d9fe2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-jre"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "6.0-alpha-3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "fernflower",
          "version": {
            "requires": "07082019"
          }
        },
        {
          "group": "nulled",
          "module": "logger",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "nulled",
          "module": "annotations",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-1.2.jar",
          "url": "injector-1.2.jar",
          "size": 408598,
          "sha512": "babe7882d7bb2b829b6252a07a3c4eed990d47651258dd1a0126ad582466a871d1ed76580b32ecf9ae354afeadf5f145d4fd6b25361035b28a01734f0d6fa75a",
          "sha256": "e3b30ac3fa262ac9ef28dad099cfa9e55533cfe4a72e9503fac38a5538aec579",
          "sha1": "8c0e6dac93a0a0a3be520d5fdd1fe93fa63a659d",
          "md5": "28e9b67a78cae6efcbd15f1655d9fe2f"
        }
      ]
    }
  ]
}
