{
  "formatVersion": "1.1",
  "component": {
    "group": "nulled",
    "module": "logger",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.1.jar",
          "url": "logger-1.1.jar",
          "size": 7352,
          "sha512": "37aad47dcb8cc1d6b57a37e2520c8d4c42943cb633f04654257f898bae17e25ff8e311d9551a9dc00c473e1c73570f3ee131d0244682282e8d843280a6277d8e",
          "sha256": "162c370dd678108940cc81bafa9f5a6dce92291f2962f10bc1e7bf20a3fbb060",
          "sha1": "8021ec8b409ceb21e6854176f739a7284eeffa33",
          "md5": "1429f8cdc343bd495416fe9535a5278e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.1.jar",
          "url": "logger-1.1.jar",
          "size": 7352,
          "sha512": "37aad47dcb8cc1d6b57a37e2520c8d4c42943cb633f04654257f898bae17e25ff8e311d9551a9dc00c473e1c73570f3ee131d0244682282e8d843280a6277d8e",
          "sha256": "162c370dd678108940cc81bafa9f5a6dce92291f2962f10bc1e7bf20a3fbb060",
          "sha1": "8021ec8b409ceb21e6854176f739a7284eeffa33",
          "md5": "1429f8cdc343bd495416fe9535a5278e"
        }
      ]
    }
  ]
}
