{
  "formatVersion": "1.1",
  "component": {
    "group": "nulled",
    "module": "logger",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.1.jar",
          "url": "logger-1.1.jar",
          "size": 7529,
          "sha512": "02366cd862cadc31450341441281259c69819c759d41ebcd241571f58c46fead56db575d95a227ad7e9dfa7655e86cd4e947a39d81a688511d4bd8fe4b9a56c7",
          "sha256": "6ef83818b3d4a329584baa8a74f0ec57ae55fcb2e4c86d273f66bd5bb4885783",
          "sha1": "ac395965368e25f7e18c81eebf0ffc49e26e6ef8",
          "md5": "a8faa360f187f34c2d3d3a531d491014"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.1.jar",
          "url": "logger-1.1.jar",
          "size": 7529,
          "sha512": "02366cd862cadc31450341441281259c69819c759d41ebcd241571f58c46fead56db575d95a227ad7e9dfa7655e86cd4e947a39d81a688511d4bd8fe4b9a56c7",
          "sha256": "6ef83818b3d4a329584baa8a74f0ec57ae55fcb2e4c86d273f66bd5bb4885783",
          "sha1": "ac395965368e25f7e18c81eebf0ffc49e26e6ef8",
          "md5": "a8faa360f187f34c2d3d3a531d491014"
        }
      ]
    }
  ]
}
