{
  "formatVersion": "1.1",
  "component": {
    "group": "nulled",
    "module": "logger",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.2.jar",
          "url": "logger-1.2.jar",
          "size": 7529,
          "sha512": "4577820df475913819c87ce136e6bff761bb0416efde6c127d152c38272e373480f205ca173020b0ac7d39489711ed9788614979adcff855aafcf5ea62538237",
          "sha256": "de2d335c0de9f4725cacb8c67281703cf075222ff015b49fdbf62bbe9622cf2a",
          "sha1": "39930f56814d558a82c13197b3c8294a3df959d3",
          "md5": "900e39f8e2e460dc3036d4a5c452583f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.2.jar",
          "url": "logger-1.2.jar",
          "size": 7529,
          "sha512": "4577820df475913819c87ce136e6bff761bb0416efde6c127d152c38272e373480f205ca173020b0ac7d39489711ed9788614979adcff855aafcf5ea62538237",
          "sha256": "de2d335c0de9f4725cacb8c67281703cf075222ff015b49fdbf62bbe9622cf2a",
          "sha1": "39930f56814d558a82c13197b3c8294a3df959d3",
          "md5": "900e39f8e2e460dc3036d4a5c452583f"
        }
      ]
    }
  ]
}
