{
  "formatVersion": "1.1",
  "component": {
    "group": "nulled",
    "module": "injector",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-1.0.jar",
          "url": "injector-1.0.jar",
          "size": 408161,
          "sha512": "a03347fe0d9320edf10f4a2455548f2dce5ef373dbe597f6fc4fecc539769539e539cc13273798e72448f4de003bdef06b7656dad1e1109dedba62ef143d4eb3",
          "sha256": "1748f9fec1ad3ed0d2fcdfc4536fb045d389c1edad97c2493a12c94ae502b6a4",
          "sha1": "ecd809b36f2cd021f97233cca7893e3f679582cd",
          "md5": "bf1fbd34eb07c7e7f3d69c997a94452c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-jre"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "6.0-alpha-3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "fernflower",
          "version": {
            "requires": "07082019"
          }
        },
        {
          "group": "nulled",
          "module": "logger",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "nulled",
          "module": "annotations",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-1.0.jar",
          "url": "injector-1.0.jar",
          "size": 408161,
          "sha512": "a03347fe0d9320edf10f4a2455548f2dce5ef373dbe597f6fc4fecc539769539e539cc13273798e72448f4de003bdef06b7656dad1e1109dedba62ef143d4eb3",
          "sha256": "1748f9fec1ad3ed0d2fcdfc4536fb045d389c1edad97c2493a12c94ae502b6a4",
          "sha1": "ecd809b36f2cd021f97233cca7893e3f679582cd",
          "md5": "bf1fbd34eb07c7e7f3d69c997a94452c"
        }
      ]
    }
  ]
}
